### ISSUE TITLE
LinkedIn Learning missing from "Sites and Courses" options

### ISSUE THREAD

**Issue by mor10** [StateOfJS/StateOfJS-Vulcan#151]
LinkedIn Learning (formerly Lynda.com) serves millions of learners across the globe, has a broad offering of CSS courses, and features courses with hundreds of thousands of yearly learners including [Christina Truong's "CSS Essential Training"](https://www.linkedin.com/learning/css-essential-training-3/) viewed by 195,000 individual learners. Its omission from the "Sites and Courses" options has been flagged for several years yet continues in the 2022 survey.

**Comment by SachaG** [comment]
The reason why it's not included is that I make the list based off people's freeform answers for the past year, and neither LinkedIn or Lynda got a lot of mentions: 

https://2021.stateofcss.com/en-US/resources/sites_courses

I'm not sure why that is to be honest, I agree since it's a large platform you'd expect it to score better.

**Comment by SachaG** [comment]
Anyway let's add it and see what happens.
