### ISSUE TITLE
Request: adding a note about Angular is not including AngularJS (1.x)

### ISSUE THREAD

**Issue by lacolaco** [StateOfJS/StateOfJS-Vulcan#26]
StateOfJS seems not to distinguish Angular and AngualrJS in the survey and there are no notes about that. 
![image](https://user-images.githubusercontent.com/1529180/69923963-da444a00-14eb-11ea-9f95-674988b7bd4c.png)

It’s unfair because 1) the name convention about Angular/AngularJS is not well-known yet. 2) Many developers have experience in years ago with AngularJS-only 3) So, it is natural that "Used it > would avoid" raises.
4) Even if they have experiences with Angular, it is not clear which Angular the survey asks about.   

I agree that today it doesn't have to survey about AngularJS because it is not a fresh technology. But I think the one line note about distinguishing is still important for clarifying the target of the survey.

Thanks.

**Comment by SachaG** [comment]
Since last year we decided the Angular/AngularJS split happened a long enough time ago that we could move on and just refer to "Angular". After all we don't make any distinction between Vue 1.0 and Vue 2.0 in the survey either, and the exact same arguments could apply to that. So I don't think it's unfair to treat Angular the same way we treat every other framework.

**Comment by lacolaco** [comment]
@SachaG Vue.js didn't its name between 1.0 and 2.0. It's natural because it is a common major version up. But the difference between AngularJS and Angular is not a common case. That Vue's example corresponds to Angular 7.0 and 8.0.
At least I would like you to understand Angular is not a version change but a new different library.

My hope was just adding one line note, not changing the survey.

**Comment by lacolaco** [comment]
I think that clarifying that StateOfJS is asking about only "Angular" brings nothing negative side. Reducing ambiguity may make the survey more reliable and worthfully. 
If there are any negative sides, I want to understand it.

**Comment by SachaG** [comment]
The issue is that if we add a note next year it will skew the data since we didn't have that note this year or last, and that will make it harder to compare trends. 

On the other hand, we did add a note to the results in 2018 to explain how the question was phrased: 

> Note that from this year on we are not be making a distinction between Angular and Angular.js anymore, while datapoints for 2016 and 2017 correspond to Angular (a.k.a. "Angular 2").

https://2018.stateofjs.com/front-end-frameworks/angular/

**Comment by lacolaco** [comment]
I can understand the concern about skewing but already it seems probably happened in the last year by dropping "AngularJS". 
That note is basically correct but it cannot be seen while answering the survey (the screenshot at the issue top.)
Note after asking is not kind. Everyone has to read the last year's result before starting survey. 
It is needed while the survey.

**Comment by lacolaco** [comment]
What I'd like to improve is the ambiguity of the "Angular" question. 
For getting a result mixed of "Angular"/"AngularJS", the current question is working.
But if StateOfJS expects a result of only "Angular", the current question is improvable.

**Comment by SachaG** [comment]
Well, whatever skewing happened this year and last year, we want to keep the same skew going forward to make it possible to compare 2020, 2019, and 2018. If we "de-skewed" 2020 by doing what you suggest it would then make it impossible to compare 2020 with 2019 and 2018 because the question was not phrased the same way. 

In other words we'd rather have ambiguity but remain consistent than change things for the sake of clarity and break continuity with past years.

**Comment by thanhpd** [comment]
> Well, whatever skewing happened this year and last year, we want to keep the same skew going forward to make it possible to compare 2020, 2019, and 2018.

May I suggest to split the Angular section into two, one for the AngularJS and another for Angular (v2 and up)?
That may be able to solve the consistency problem since we can combine the results of these two to get the old Angular results defined by the existing surveys, while individuals who would like to gain more insight into the Angular ecosystem can understand better the differences.

> If we "de-skewed" 2020 by doing what you suggest it would then make it impossible to compare 2020 with 2019 and 2018 because the question was not phrased the same way.

I do not quite agree with this. Isn't the whole point of surveys, in general, is to collect results as objective as possible? If the data is not being truthful then what's the point of collecting them? The naming case of Angular/AngularJS is special, but if the same situation also happens to React and Vue.js then keeping the same survey format for the sake of consistency can be bad.

More clarity is good for users and for developers, those who can take a look at the results and make decisions for their projects. Technology keeps changing, so the survey format should also be updated to reflect those changes. I do agree with your concerns about allowing people to see the trend but its importance may be overestimated, especially the dataset collected each year may come from different groups.

**Comment by tayambamwanza** [comment]
> Well, whatever skewing happened this year and last year, we want to keep the same skew going forward to make it possible to compare 2020, 2019, and 2018. If we "de-skewed" 2020 by doing what you suggest it would then make it impossible to compare 2020 with 2019 and 2018 because the question was not phrased the same way.
> 
> In other words we'd rather have ambiguity but remain consistent than change things for the sake of clarity and break continuity with past years.

Ambiguity defeats the whole point of a survey.

**Comment by gionkunz** [comment]
> Since last year we decided the Angular/AngularJS split happened a long enough time ago that we could move on and just refer to "Angular". After all we don't make any distinction between Vue 1.0 and Vue 2.0 in the survey either, and the exact same arguments could apply to that. So I don't think it's unfair to treat Angular the same way we treat every other framework.

Hi. I know this is a confusing topic, but it's actually really problematic not to mention the Angular version in a survey. Most people who worked with AngularJS will associate their experience with the term "Angular".

If I look at the projects of my clients, there are still a shockingly high number of AngularJS (1.x) projects out there and EoL of AngularJS is in 2021 (July 1, 2018 — June 30, 2021 AngularJS 1.7 LTS Period).

I'm maybe the wrong person to tell, since I'm bias to Angular because of my fantastic experience with it, but I seriously doubt the quality of your data given the ambiguity.

**Comment by dtomaszewski** [comment]
> Since last year we decided the Angular/AngularJS split happened a long enough time ago that we could move on and just refer to "Angular". After all we don't make any distinction between Vue 1.0 and Vue 2.0 in the survey either, and the exact same arguments could apply to that. So I don't think it's unfair to treat Angular the same way we treat every other framework.

I don't think that this response is valid. Nobody wants to split Angular 7 and 8. I'ts just a coincidence that AngularJS and Angular have similar names as they're totally different frameworks. Angular team naming decision while creating Angular 2+ now makes Your survey unreliable.

If Angular team would go with different (Ralugna) name in the past You'd still connect them together ? On what basis ?

**Comment by dtomaszewski** [comment]
Connect React, Preact and React native together, their names are almost identical.

**Comment by tayambamwanza** [comment]
@dtomaszewski My friend I'm just going to speak straight to you about this one, their biased against Angular so it doesn't really matter to them. 

So don't waste your time trying to reason with them.

Also don't stress about statistics they can often be misleading, if extra effort isn't made to remove inconsistencies like this

"Lies, damned lies, and statistics" - Mark Twain

My advice, just continue enjoying Angular and ignore the survey, I think a better one is stack overflow anyways.

**Comment by Matmo10** [comment]
>In other words we'd rather have ambiguity but remain consistent than change things for the sake of clarity 

"We'd rather be consistently inaccurate than have clear, factual data going forward"

lol what? I can appreciate that the StateOfJS is just a side project for a few people, but if you market and publish it as some objective source of truth for the JS community, it's kind of disingenuous. I realize differentiating Angular and AngularJS could add quite a bit of extra work on the implementation side, but if that's the roadblock here let's just be upfront about it.

**Comment by mmiszy** [comment]
@SachaG If you sum up weekly NPM downloads of Preact, Svelte, and Ember you still get a lower number than AngularJS weekly downloads. And yet Preact, Svelte or Ember get to be separate items in the questionnaire and AngularJS does not.

Moreover, I think it's fair to say that Angular and AngularJS have less in common than React and Preact, and yet the later get to be separate items in the questionnaire.

In my opinion, it's really confusing and inconsistent. There are no reasons to treat Angular and AngularJS as a single framework (they're not, they're two completely different libraries)

**Comment by Vorakor** [comment]
@SachaG I hope you realize that if you can't provide accurate and meaningful results in this category than the community will produce something that replaces this.  I'm also extremely disappointed in the slant of this data set, I don't mind learning React or Vue or any of the other frameworks, but you absolutely cannot loop AngularJS (1.x versions) with Angular (2.x and above version), they simply aren't the same thing.  And for those that used AngularJS and then left to another library, you are now misrepresenting Angular to them, making them think that it's more of the same old same old instead of a complete departure from how Angular used to do things.  This is also damaging to Angular's reputation as well as to any entity using it, this went from an accurate data set to "Use React instead of Angular because it's more popular" in the eyes of companies, when in fact the data set is inaccurate and incomplete.  Continuing to loop the two together is irresponsible and unprofessional given this is supposed to give an accurate state of JS, regardless of how difficult it might be to change the data set in order to provide accurate results.

**Comment by Twista** [comment]
What's the value of the survey then?

**Comment by SachaG** [comment]
> Moreover, I think it's fair to say that Angular and AngularJS have less in common than React and Preact, and yet the later get to be separate items in the questionnaire.

I don't dispute that, but why wouldn't we be able to drop AngularJS from our survey? After all we don't have jQuery, Backbone, or Knockout either.

**Comment by vrch** [comment]
@SachaG Unfortunately Angular's naming convention is still confusing to some people, you could at least add some kind of disclaimer next to Angular, that name Angular applies only to "new" Angular and AngularJS isn't part of the survey anymore

**Comment by SachaG** [comment]
> you could at least add some kind of disclaimer next to Angular, that name Angular applies only to "new" Angular and AngularJS isn't part of the survey anymore

That's a valid solution. It would still mess with the continuity from one year to another but I'll consider it.

**Comment by perjerz3434** [comment]
https://medium.com/@sachagreif/three-controversial-charts-from-the-state-of-js-2018-ec9dda45749

```
First, here’s how the Angular question has been addressed over all 3 years of the survey:
2016: asked about both Angular and AngularJS, in two separate questions
2017: asked about both Angular and AngularJS, in two separate questions
2018: only asked about Angular
```

In any case, I’ll agree that we did do a poor job of explaining the whole issue, and for that we apologize.

The same mistake is made.

**Comment by SachaG** [comment]
> The same mistake is made.

You're right, we didn't improve this aspect compared to 2018. There was a lot to work on on a tight deadline and I never got to thinking about this issue specifically, so I apologize for that. 

I also think a lot of the complaining about this particular issue over the years have made me overly dismissive of some of the valid points made here, and re-reading that 2018 post I think I probably had a more balanced opinion there. 

So anyway my conclusion is that in 2020 we will have a note next to Angular specifying that it does *not* refer to AngularJS. Hopefully that will be enough to clear up the confusion. And if I somehow forget again feel free to link to this comment and publicly shame me.

**Comment by tayambamwanza** [comment]
> > The same mistake is made.
> 
> You're right, we didn't improve this aspect compared to 2018. There was a lot to work on on a tight deadline and I never got to thinking about this issue specifically, so I apologize for that.
> 
> I also think a lot of the complaining about this particular issue over the years have made me overly dismissive of some of the valid points made here, and re-reading that 2018 post I think I probably had a more balanced opinion there.
> 
> So anyway my conclusion is that in 2020 we will have a note next to Angular specifying that it does _not_ refer to AngularJS. Hopefully that will be enough to clear up the confusion. And if I somehow forget again feel free to link to this comment and publicly shame me.

@SachaG 
Nice one, thanks for considering, I remember last time watching fireships .io video which had the title "the real state of js" and one of the issues mentioned was that the author of the survey are all mainly from react ecosystem, one way to combat bias would be to include experts from other ecosystem, at least 1 react, angular and Vue centric Dev (big three) maybe could look into this for other tech, that way you get a broader perspective instead of an echo chamber for certain technology

**Comment by rofrol** [comment]
https://docs.google.com/spreadsheets/d/1WE8VBrVwmeINHFUGXCuQWIYxT-3ukWbHSej4qPJYTJk

**Comment by tayambamwanza** [comment]
@lacolaco so it does matter to separate after all (Stack overflow 2020)

![Screenshot from 2020-06-27 18-49-01](https://user-images.githubusercontent.com/11971384/85927633-b5f4f400-b8a7-11ea-9262-cf47a9c527ad.png)

**Comment by SachaG** [comment]
We're taking feedback for the 2020 edition of the survey: https://github.com/StateOfJS/StateOfJS-2020/issues/1

Let's solve this Angular issue once and for all!
